#!/usr/bin/env bash
# This script is displaying " Best school" 10 times, but for the 9th iteration, displays "Best school" and then "Hi" on a new line
i=1
while [ $i -le 10 ]
do
    echo "Best school"
    if [ $i -eq 9 ]
    then
       echo "Hi"
    fi
    ((i++))
done
