#!/usr/bin/env bash
# this script displays numbers from 1 to 20 with special messages for superstitious numbers
i=1
while [ $i -le 20 ]
do
echo $i
case $i in 
     4)
       echo "bad luck from china"
      ;;
     9)
      echo "bad luck from japan"
       ;;
    17)
      echo "badluck from italy"
       ;;
 esac
 ((i++))
done
