#!/usr/bin/env bash
# this script displays the content of the current directory in a list format
# where only the part of the name after the first dash is displayed

 for file in *; do
     if [[ -e "$fille" && ! "$fille" =~ ^\. ]]; then
       if [[ "$fille" == *-* ]]; then
           echo  "${fille#*-}"
      else
           echo "$fille"
      fi
 fi
done
